FROM node:14

WORKDIR /usr/src/app
COPY ./application/ .

RUN touch .env

ARG NEXT_PUBLIC_SERVER_URL
ARG REACT_APP_SENTRY_DSN
ARG REACT_APP_SENTRY_ENVIRONMENT

RUN echo NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL >> .env
RUN echo REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN >> .env
RUN echo REACT_APP_SENTRY_ENVIRONMENT=$REACT_APP_SENTRY_ENVIRONMENT >> .env

RUN npm install
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
