import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import Footer from "../../components/footer";
import Legal from "../../components/Legal";

export default function SolidPrivacyPolicy() {
  const [modalStatus, setModalStatus] = useState(false);

  const handleModalStatus = () => {
    setModalStatus(false);
  };

  return (
    <>
      <Head>
        <title>Oval: Solid website & dashboard terms of use</title>
      </Head>
      <nav className="flex justify-between items-center px-12 md:px-24 py-5 bg-white">
        <div className="flex space-x-2">
          <h3 className={`text-grey-dark cursor-pointer`}>Oval</h3>
        </div>
        <div className="space-x-4 flex">
          <Link href="/">
            <button className="rounded-lg py-2 px-3 text-darkGray bg-blue-ocean border border-gray-100">
              Home
            </button>
          </Link>
        </div>
      </nav>

      <main className="pt-8 px-12 bg-white min-h-screen md:overflow-x-hidden">
        <div className="w-4/5 mx-auto my-0 max-w-[700px] min-w-[300px]">
          <Legal active="solid-platform-terms-of-use" />
          <h3 className="mb-4 text-center">Solid platform terms of service</h3>
          <p className="mb-4">Last updated: 05/01/21</p>
          <p className="mb-4">
          If you are using  (1) a website or mobile application that uses Solid to enable your banking needs; (2) an account created on websites; or (3) you are otherwise using our website and software services under the Terms of Service. By using these services, you agree to Solid’s Terms of Service and Privacy  Policy (collectively, the “Terms of Service”), all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. We may update these Terms of Service from time to time and it is your responsibility to check for updates.           </p>
          <p className="mb-4">
          This policy describes the types of information we may collect from you or that you may provide when you visit the website solidfi.com, or interact with us via the Solid Banking App, Solid Banking Services, Solid Dashboard, Facebook, Instagram, Twitter, or LinkedIn (our <strong>"Website"</strong>) and our practices for collecting, using, maintaining, protecting, and disclosing that information.
          </p>
          <p className="mb-4">If you do not agree to these Terms of Service, you must immediately stop using our services.</p>
          <p className="mb-4">NOTICE OF BINDING ARBITRATION </p>
          <p>
          ANY CLAIM, DISPUTE OR CONTROVERSY OF WHATEVER NATURE ARISING OUT  OF OR RELATING TO THE TERMS OF SERVICE SHALL BE RESOLVED BY FINAL  AND BINDING ARBITRATION IN ACCORDANCE WITH THE PROCESS DESCRIBED  IN THE SECTION TITLED “BINDING ARBITRATION” BELOW. PLEASE READ THE  SECTION TITLED “BINDING ARBITRATION” CAREFULLY. 
        
          </p>

          <p className="mb-4"><strong>1. Introduction to “Solid”</strong></p>
          <p className="mb-4">Solid Financial Technologies, Inc. and our affiliates or subsidiaries (collectively “Solid,” “we,” “us,” or “our”) is banking as a software (BaaS) layer between banks, and the financial technology platforms using our services (“Platform”).&nbsp; We provide Platforms banking services (e.g. bank transfers or accounts) to you through Solid’s bank partners&nbsp; (collectively “Banks”)</p>
          <p className="mb-4">Check out our website (solidfi.com) or feel free to email us at chat@solidfi.com to learn more about Solid.&nbsp</p>
          <p className="mb-4"><strong>2. Your customer relationship to Solid&nbsp;</strong></p>
          <p className="mb-4">By using our services offered through Platforms or our website or mobile application, you became a customer of Solid. You agree to these Terms of Service when you use the services. You understand that all bank and transaction-related services are provided directly by the Bank, except as it relates to specific services provided to you by your Platform. Similarly, Platform is responsible for providing their services to you pursuant to your agreements with Platform. Solid’s services allow you to easily communicate with banks and other financial institutions through  Platforms. By using our service, you grant us the right, power,  and authority to act on your behalf to access and transmit your personal and financial information, and requests for services between Bank, Platform, and any other financial institutions (as applicable). </p>
          <p className="mb-4"><strong>3. Your representations and promises or affirmations to us.&nbsp;</strong></p>
          <p className="mb-4">By using our services or by accessing Solid’s or a Platform’s  website or phone application, you acknowledged and agree that: </p>
          <p className="mb-4"><strong>a. Restriction on acceptance and use of our services.&nbsp;</strong></p>
          <p className="mb-4">You are at least 18 years old (or legal age of capacity of your state) and you have the right, authority, and capacity to enter into these Terms of Service. If you are accepting these Terms of  Service on behalf of any legal entity, including any company,  organization, government, or governmental agency, you have been  authorized to do so and to act on behalf of such legal entity:</p>
          <p className="mb-4"><strong>b. True and accurate information. </strong></p>
          <p className="mb-4">The information and instructions you provide us are true, accurate,  and complete, as you are solely responsible for such information and instructions. Additionally, you will provide all information requested by us, such as your name, email address, phone number,  date of birth, social security number or tax identification number,  photo ID, online login credentials or your account and routing numbers for your bank or credit union account (“Bank Account”),  and such other information as we may request from time to time.  You agree to update us if the information changes (collectively,  your “User Data”). We may use third parties to verify all or a  portion of your information. </p>
          <p className="mb-4 font-bold">c. Verification of your information.</p>
          <p className="mb-4">We may share your information with your Platform, Bank, our subsidiaries, and other third parties to verify your identity and/or your account information to provide our services to you as further detailed in our Privacy Policy. Sharing this information  is necessary to open an Account and to provide transaction-related  services as further detailed in the Section “USA PATRIOT Act  notice.” </p>
          <p className="mb-4 font-bold">d. Password security. </p>
          <p className="mb-4">If Platform or we provide you with login credentials (e.g. username, password or PIN) to access our services, (i) you will keep this information secure and confidential; (ii) you will not share such information with third parties; and (iii) you understand that you are responsible for all activity any person conducts using your login credentials to access our services, regardless of whether or not you authorized the activity. <strong><em>We will never ask you for your login credentials by phone or email.&nbsp;</em></strong></p>
          <p className="mb-4 font-bold">e. Authorization to debit your account. </p>
          <p className="mb-4">By using our transactions services to send funds via the Automated  Clearing House (“ACH”) from your linked Bank Account(s) to your  Account, Platform, or a third party, you authorize us (as an agent of  Bank) to debit the Bank Account indicated by you for the amount and on the date provided by you. You understand that because this will be an electronic transaction, and funds may be withdrawn from your account as soon as the above-noted transaction date. You will not dispute your Platform, Bank, or Solid debiting my account,  so long as the transaction corresponds to the terms indicated in the transaction web form provided to you. </p>
          <p className="mb-4 font-bold">f. Limits on access to services. </p>
          <p className="mb-4">We may limit or suspend your access to our services or take other actions against you if the information you provide us is incorrect or you otherwise breach these Terms of Service as further detailed in these Terms of Service. </p>
          <p className="mb-4 font-bold">g. Compliance with the law and your agreements.</p>
          <p className="mb-4">Your use of our services does not violate any laws or regulations or any agreements with any third parties. </p>
          <p className="mb-4 font-bold">h. Platform services are not endorsed. </p>
          <p className="mb-4">We do not provide any endorsements or guarantees for any individual or entity using Solid’s services (including the Platform you accessed to use our services), nor any third party offers, goods or services featured on our websites. Information regarding third-party offers, goods, and services is provided on our websites for informational purposes only, and may not be true, accurate, or reliable. </p>
          <p className="mb-4 font-bold">i. USA PATRIOT Act notice. </p>
          <p className="mb-4">Important information about procedures for using our services under the USA PATRIOT Act of 2001: To help the government fight the funding of terrorism and money laundering activities, federal law requires all financial institutions to obtain, verify, and record information that identifies each person who opens an account. What this means for you: When you use our services, we will ask for your name, address, date of birth, and other information that will allow us to identify you. We may also ask to see a form of identification with your photograph or other identifying documents. </p>
          <p className="mb-4 font-bold">4. Your conduct. </p>
          <p className="mb-4">You understand and agree that you will not: </p>
          <p className="mb-4"><strong>a. </strong>Use our services, without Solid’s prior written&nbsp; consent, to transact with or operate services relating&nbsp; to (i) credit repair, (ii) debt consolidation, (iii)&nbsp; payday loans, (iv) title loans, (v) telemarketing, (vi)&nbsp; tobacco sales, (vii) travel clubs, (viii) sweepstakes, (ix) choice of law, (x) marijuana or controlled substance&nbsp; supply, (xi) tribal and entities that are not governed&nbsp; by the U.S. or states, (xii) mail order or telephone&nbsp; order companies, (xiii) business located outside of the&nbsp; U.S., (xiv) adult entertainment, (xv) stored value&nbsp; cards, (xvi) illegal or fraudulent goods or services,&nbsp; including, but not limited to, illegal substances,&nbsp; counterfeit goods, stolen goods, illegal or controlled&nbsp; substances, and substances that pose a risk to consumer&nbsp; safety (including synthetics, “potpourri not for human&nbsp; consumption”, and other similar items), illegal online&nbsp; gambling / wagering, pyramid schemes, counterfeit goods,&nbsp; unlicensed sale of firearms or weapons, (xvii) any type&nbsp; of money laundering, or (xviii) other businesses that&nbsp; operate or engage in any business regulated by FinCEN,&nbsp; including money service businesses, e-money business,&nbsp; and businesses selling money orders or traveler’s&nbsp; checks, and virtual or crypto-currency marketplaces and&nbsp; exchanges;</p>
          <p className="mb-4"><strong>b. </strong>Provide false or inaccurate information to us, including an attempt to falsify your identity, such as by providing&nbsp; false account information or false documents;&nbsp;</p>
          <p className="mb-4"><strong>c. </strong>Defraud us, Bank, or other Solid users in any way;&nbsp;</p>
          <p className="mb-4"><strong>d. </strong>Receive or attempt to receive duplicate compensation for&nbsp; a disputed payment from the recipient, Solid, Bank,&nbsp; and/or other financial institutions;&nbsp;</p>
          <p className="mb-4"><strong>e. </strong>Engage in activity that indicates, in Solid or the&nbsp; Bank’s discretion, that there may be a high level of risk&nbsp; associated with you, your Account, or any of your Solid&nbsp; account activity; or&nbsp;</p>
          <p className="mb-4"><strong>f. </strong>Otherwise breach the terms of these Terms of Service or the policies herein.&nbsp;</p>
          <p className="mb-4"><strong>5. Our services.&nbsp;</strong></p>
          <p className="mb-4">Solid provides software services to you and Platforms to give you the ability to send and receive funds from third parties, in addition, to open up an Account. All funds transfer services are provided by Bank, as Solid does not receive, hold, or transmit funds. Our software allows you to send funds transfer instructions to Bank. Any funds balance displayed by Solid’s software are held in your Account, or otherwise held by Bank or Platform for your benefit, as applicable (“Account Balance”).&nbsp;</p>
          <p className="mb-4">Solid MAKES NO REPRESENTATIONS OR WARRANTIES RELATING TO YOUR&nbsp; FUNDS OR ACCOUNT BALANCES INCLUDING FEDERAL DEPOSIT INSURANCE&nbsp; CORPORATION (“FDIC”) INSURANCE COVERAGE. SUCH REPRESENTATIONS AND&nbsp; WARRANTIES MAY BE FOUND IN YOUR SPECIFIC ACCOUNT AGREEMENT OR&nbsp; AGREEMENT WITH YOUR PLATFORM. UNLESS NOTIFIED OTHERWISE BY SUCH&nbsp; AGREEMENTS, YOUR ACCOUNT BALANCES MAY LOSE VALUE IN THE EVENT BANK,&nbsp; THE BROKER-DEALER, OR PLATFORM ENTERS A RECEIVERSHIP.&nbsp;</p>
          <p className="mb-4"><strong>a. Bank account services.&nbsp;</strong></p>
          <p className="mb-4">We provide software services to facilitate your requests for services relating to your Account as detailed in such agreements.&nbsp; We are not responsible or liable if your request for such services is limited, delayed, or denied for risk, compliance, or other reasons.&nbsp;</p>
          <p className="mb-4"><strong>b. Transaction-only services.&nbsp;</strong></p>
          <p className="mb-4">As an agent of a Bank, we may provide you with services to process transactions to or from your Platform or a third party in addition to your Account. In certain circumstances relating to our transaction services, your funds may be held by Platform or Bank for your benefit and an account balance may be displayed to you by our software. To provide services under this section, we may collect personally identifiable information, your Bank Account login credentials or account and routing numbers for your Bank&nbsp; Account, or other User Data information as we may request from time to time as further detailed in these Terms of Service and our&nbsp; Privacy Policy. Transactions processed via Automated Clearing House&nbsp; (“ACH”) will be processed in accordance with such timeframes except as otherwise noted in these Terms of Service. Such transaction services may be limited, delayed, or denied for risk and compliance reasons that we may not be able to disclose to you. You understand that the transactions may be limited, delayed, or denied and expressly disclaim any claims relating to such actions. We are not responsible for reviewing the accuracy of the transactions (amount,&nbsp; date, or the sender or receiver of funds). Additionally, we are not responsible if the receiver of funds rejects your transaction.&nbsp;</p>
          <p className="mb-4"><strong>c. Other services.&nbsp;</strong></p>
          <p className="mb-4">We may from time to time offer additional services or remove services without prior notice to you. You agree to be bound by the terms and conditions of such services as they may be offered to you.&nbsp;</p>
          <p className="mb-4"><strong>6. Fees.&nbsp;</strong></p>
          <p className="mb-4">Fees for services offered under your Account are detailed in the specific Account agreements. If you use our Transaction services listed in Section 4(b), you may be charged a transaction fee by  Platform or us as detailed in your agreement with Platform.  Transactions completed on our website or mobile application may include a transaction fee as detailed when you make a transaction request. </p>
          <p className="mb-4"><strong>7. Reversals</strong>.&nbsp;</p>
          <p className="mb-4">In the event that a sender or the sender’s financial institution requests a reversal of payment or Solid decides against you in a  dispute against you, we reserve the right to charge you a $15.00  fee in addition to the full amount of the transaction  (collectively, the “Reversal Dues”). You agree to immediately reimburse for the Reversal Dues. Additionally, you authorize us to recover any Reversal Dues outstanding to Solid or Bank by debiting your available Account Balance. If you have an insufficient Account  Balance, you authorize Solid and our Bank to take any of the  following actions to recover the remaining amounts from you: </p>
          <p className="mb-4"><strong>a. </strong>Debit the Bank Account(s) linked to our services;&nbsp;</p>
          <p className="mb-4"><strong>b. </strong>Suspend your use of our services and require your immediate payment; or&nbsp;</p>
          <p className="mb-4"><strong>c. </strong>Engage in collection efforts.&nbsp;</p>
          <p className="mb-4"><strong>8. Protecting you and resolving disputes.&nbsp;</strong></p>
          <p className="mb-4">Solid is always looking for ways to protect you from abusive business practices, security-related issues, and other issues you may encounter with Platform and our Banks. If you have a complaint against how Platform or Bank is providing services to you or using your User Data, just let us know by emailing us at&nbsp; legal@solidfi.com per below. We cannot warranty or guarantee anything under this section, but if we are able to help, we will work with you to resolve your complaint so long as such assistance is commercially reasonable and does not violate any agreements with third parties, regulations, or laws. Disputes relating to your Account shall be governed by your specific account agreements.&nbsp; Below is more information on how we can try to help you with other&nbsp; Disputes (as defined below).&nbsp;</p>
          <p className="mb-4"><strong>a. Dispute resolution</strong>.&nbsp;</p>
          <p className="mb-4">You understand and agree that we are not responsible for the goods or services that you pay for using our services, including but not limited to those offered by your Platform and other third parties.&nbsp; Each Platform and seller that you purchase from is responsible for providing the goods and services that you purchase and for providing all customer service related to those goods and services.&nbsp; We recommend that you review Platform’s and, if applicable, a&nbsp; seller’s policies before completing your purchase. You are&nbsp; responsible for resolving any disputes that you may have with a&nbsp;</p>
          <p className="mb-4">Platform or a seller. If you have exhausted all options for resolving a complaint about abusive business practices, security-related issues, or other dispute with a Platform or a seller, you may choose to file a dispute claim with Solid (“Dispute”) by following the steps in this “Disputes” Section.&nbsp;</p>

          <p className="mb-4"><strong>b. Release of Solid.&nbsp;</strong></p>
          <p className="mb-4">By filing a Dispute, you understand and agree that:&nbsp;</p>
          <p className="mb-4">You are asking us to assist in resolving the dispute in its sole&nbsp; discretion and that such assistance or Solid’s decision may not&nbsp; be satisfactory to you;&nbsp;</p>
          <p className="mb-4">Solid’s assistance in resolving the dispute does not guarantee&nbsp; any particular outcome or any action on our part; and&nbsp;</p>
          <p className="mb-4">You release Solid and our officers, directors, agents, employees,&nbsp; subsidiaries, and suppliers from all claims, demands, and damages of any kind arising out of your dispute with a seller and Solid’s review of your Dispute.&nbsp;</p>
          <p className="mb-4"><strong>c. How to file a Dispute. </strong>To file a Dispute, follow these&nbsp; steps:&nbsp;</p>
          <p className="mb-4"><strong>i. Abusive business practices, security issues, or other non-transaction-related disputes. </strong>If you&nbsp; have a complaint about a Platform relating to&nbsp; abusive business practices, security issues,&nbsp; handling of your User Data, or related issues,&nbsp; email us at legal@solidfi.com with the&nbsp; following information:&nbsp;</p>
          <p className="mb-4"><strong>1. </strong>The email associated with your account;&nbsp;</p>
          <p className="mb-4"><strong>2. </strong>The name of the website, mobile application, and Platform relating to such Dispute;&nbsp;</p>
          <p className="mb-4"><strong>3. </strong>The details of your Dispute with the&nbsp; Platform, including any steps already taken to resolve the issue, and copies of&nbsp; supporting documentation (e.g. email&nbsp; correspondence, related agreements, and&nbsp;&nbsp; promises or affirmations, etc.); and</p>
          <p className="mb-4"><strong>4. </strong>How these issues have negatively affected you.&nbsp;</p>
          <p className="mb-4"><strong>ii. Transaction-related disputes or unauthorized activity. </strong>Within 45 days of the original disputed&nbsp; transaction or immediately if the Dispute relates to unauthorized activity, email us at chat@solidfi.com with the following&nbsp; information:&nbsp;</p>
          <p className="mb-4"><strong>1. </strong>The email associated with your account and&nbsp; names of both parties, if available;&nbsp;</p>
          <p className="mb-4"><strong>2. </strong>The name of the website, phone application, and Platform relating to such Dispute;&nbsp;</p>   
          <p className="mb-4"><strong>3. </strong>The transaction ID number;&nbsp;</p>
          <p className="mb-4"><strong>4. </strong>The amount of the transaction; and&nbsp;</p>
          <p className="mb-4"><strong>5. </strong>The details of the unauthorized activity or your disagreement with the recipient, including any steps already taken to resolve the issue, and copies of supporting documentation (e.g. when you first noticed such unauthorized activity, email correspondence, receipts, shipping confirmations, etc.).&nbsp;</p>
          <p className="mb-4">Provide any additional information or documentation that we may request. Once Solid has decided the outcome of the&nbsp; Dispute, the parties will be notified of the decision. You are required to comply with the decision and complete any actions required by such decision.&nbsp;</p>
          <p className="mb-4"><strong><em>All disputes relating to an Account shall be governed by the specific Account agreement and this section shall not apply.&nbsp;</em></strong></p>
          <p className="mb-4"><strong>9. Your liability and actions against you.&nbsp;</strong></p>
          <p className="mb-4"><strong>a. Your liability.&nbsp;</strong></p>
          <p className="mb-4">You are responsible for all Reversal Dues, claims, fees,  fines, penalties, and other liabilities incurred by Solid, Bank,  other Solid users, a Platform, or third parties arising from your breach of these Terms of Service or your use of our services.  You agree to reimburse Solid, Bank, other Solid users,  Platforms, or third parties for any and all such liability. </p>
          <p className="mb-4 font-bold">b. Actions we may take. </p>
          <p className="mb-4">If we determine, in our sole discretion, that you may have breached these Terms of Service, that you or your account activity presents risk or security concerns, or if we are unable to verify your identity, we may take actions to protect Solid, Bank, Platforms,  our users, or other third parties from Reversal Dues, claims,  fines, penalties, and any other liability. These actions may  include, but are not limited to, the following:</p>
          <p className="mb-4"><strong>i. </strong>Suspending your access to your Account or other&nbsp; Solid related services;&nbsp;</p>
          <p className="mb-4"><strong>ii. </strong>Suspending your access to your funds held in your&nbsp; Account, or otherwise held with Bank or Platform for your benefit for up to 90 days;&nbsp;</p>
          <p className="mb-4"><strong>iii. </strong>Taking action as set out in the “Reversals”&nbsp; Section to recover amounts that you owe;&nbsp;</p>
          <p className="mb-4"><strong>iv. </strong>Closing your Account held by Bank or Platform for&nbsp; your benefit;&nbsp;</p>
          <p className="mb-4"><strong>v. </strong>Contacting Platforms, our users or third parties&nbsp; who have purchased goods or services from you, contacting the financial institution associated&nbsp;&nbsp;</p>
          <p className="mb-4">with your Bank Account(s), and/or warning other Solid users, law enforcement, or other impacted&nbsp; third parties of your actions;&nbsp;</p>
          <p className="mb-4"><strong>vi. </strong>Refusing to provide our services to you in the&nbsp; future; and&nbsp;</p>
          <p className="mb-4"><strong>c. Notice of limit or suspension. </strong>We will provide you with notice if we take any of the above actions against your&nbsp; Account or other accounts held by Bank or Platform for your benefit. If we limit or suspend such accounts, we will provide you with notice of our action.&nbsp;</p>
          <p className="mb-4"><strong>10. Your privacy + our Privacy Policy.&nbsp;</strong></p>
          <p className="mb-4">Solid takes your privacy seriously. To learn more about what information we may collect, how we use your information, and how we share your information with Platform or to open your Account,  please review our Privacy Policy found at  https://solidfi.com/privacy. </p>
          <p className="mb-4 font-bold">11. Solid services are in the US Only. </p>
          <p className="mb-4">Solid’s services are based in the United States of America. We make no claims whether these services can be appropriately used outside of the United States. If you access our services from outside of the United States, you do so at your own risk. You are solely responsible for ensuring compliance with local laws. </p>
          <p className="mb-4 font-bold">12. Solid can terminate these Terms of Service at will. </p>
          <p className="mb-4">We reserve the right, at our sole discretion, to restrict, suspend,  or terminate these Terms of Service and your access to all or any part of our services, at any time and for any reason without prior notice or liability. We reserve the right to change, suspend, or discontinue all or any part of our services at any time without prior notice or liability. </p>
          <p className="mb-4 font-bold">13. Terminating your agreement with Solid. </p>
          <p className="mb-4">If you wish to terminate your use of the services and the Terms of  Service, email us at legal@solidfi.com. However, if you terminate the Terms of Service with Solid, this will result in your Account Agreement being terminated and may impair your ability to use Platform’s services. You accept sole responsibility and any liabilities resulting from an impairment of Platform’s services or termination of your agreements with Platform, to the fullest extent permitted by law. </p>
          <p className="mb-4 font-bold">14. Terminating your agreement with Platform or your  Account. </p>
          <p className="mb-4">If you wish to terminate your agreement with Platform or your  Account, you must notify the parties of such agreements in accordance with such agreements. </p>
          <p className="mb-4 font-bold">15. Notice + electronic communication. </p>
          <p className="mb-4">To the fullest extent permitted by law, these Terms of Service,  notices, and other communications (collectively, “communications”)  from Solid to you regarding these Terms of Service may be provided to you electronically via Solid, Bank, or Platform (on behalf of  Solid), and you consent and agree to receive those communications in an electronic form. Electronic communications may be posted on the page you are on now and the pages within the Platform’s website or application, pages within the Solid website  (https://solidfi.com/) or applications, and/or delivered by  Solid, Bank, or the Platform (on behalf of Solid) to your email address(es) provided to Platform and us. You may download or print a paper copy of any electronic communication and retain it for your records. All communications in electronic format will be considered to be "in writing," and to have been received no later than twenty-four (24) hours after posting or dissemination, whether or not you have received or retrieved the communication. Solid reserves the right to provide communications in paper format. You agree to give us notice of any change of your postal or email address. </p>
          <p className="mb-4">Your consent to receive communications electronically is valid until you revoke your consent by notifying us of your decision to do so. If you revoke your consent to receive communications electronically, Solid may terminate your right to use the services under these Terms of Service and, as a result, your ability to use the Bank or Platform services, and you accept sole liability for resulting from an involuntary termination of the  Bank’s or Platform’s services, to the extent permitted by law. </p>
          <p className="mb-4">You may give notice to Solid by emailing Solid at  legal@solidfi.com </p>
          <p className="mb-4">“Business Day” for the purpose of these Terms of Service means every day is a business day except Saturdays, Sundays, and federal and state holidays.</p>
          <p className="mb-4 font-bold">16. Modifications.</p>
          <p className="mb-4">Solid may revise these terms of Service at any time without notice. By using the Platform’s or Bank’s services,  Solid services or website, you are agreeing to be bound by the then current version of these Terms of Service and any amendments to the Terms of Service upon your continued use of our services. </p>
          <p className="mb-4 font-bold">17. IMPORTANT LEGAL PROVISIONS</p>
          <p className="mb-4 font-bold">a. NO WARRANTIES. </p>
          <p className="mb-4">THE SERVICES UNDER THE TERMS OF SERVICE, Solid’S WEBSITE, AND ITS  CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT  ANY WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE WARRANTY OF TITLE, MERCHANTABILITY, NON INFRINGEMENT OF THIRD PARTIES’ RIGHTS, AND FITNESS FOR PARTICULAR  PURPOSE. </p>
          <p className="mb-4">THE Solid SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE”,  WITHOUT ANY REPRESENTATION OF WARRANTY, WHETHER EXPRESS, IMPLIED,  OR STATUTORY. USE OF THE Solid SERVICES IS AT YOUR OWN RISK.  Solid, BANKS, AND OUR AND THEIR RESPECTIVE OFFICERS, DIRECTORS,  AGENTS, EMPLOYEES, AND SUPPLIERS, SPECIFICALLY DISCLAIM ANY IMPLIED  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,  AND NON-INFRINGEMENT. NEITHER Solid NOR BANK HAVE CONTROL OF, OR  LIABILITY FOR, ANY PRODUCTS OR SERVICES OFFERED BY PLATFORMS OR  THAT ARE PAID FOR USING OUR SERVICES AND CANNOT ENSURE THAT ANY  PLATFORM OR OTHER THIRD PARTY YOU TRANSACT WITH WILL COMPLETE THE  TRANSACTION. NEITHER Solid NOR BANK REPRESENT OR WARRANT THAT  OUR SERVICES WILL MEET YOUR REQUIREMENTS, BE CONTINUOUS,  UNINTERRUPTED, SECURE, TIMELY, OR ERROR-FREE, OR THAT DEFECTS WILL  BE CORRECTED. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN,  OBTAINED BY YOU FROM Solid OR THROUGH OUR SERVICES WILL CREATE  ANY WARRANTY NOT EXPRESSLY STATED HEREIN. NEITHER Solid NOR BANK  SHALL BE RESPONSIBLE FOR ANY SERVICE INTERRUPTIONS OR SYSTEM  FAILURES THAT MAY AFFECT THE PROCESSING, COMPLETION, OR SETTLEMENT  OF OUR SERVICE TRANSACTIONS. THIS DISCLAIMER OF WARRANTY SECTION  SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE  JURISDICTION </p>
          <p className="mb-4 font-bold">b. Force majeure. </p>
          <p className="mb-4">You understand and agree we will not be held responsible for any losses or damages resulting from suspension of service due to extraordinary events or circumstances beyond our control. In such an event, Solid or Bank may suspend the services and access to your Account held by Bank or Platform for your benefit. </p>
          <p className="mb-4 font-bold">c. LIMITATION OF LIABILITY. </p>
          <p className="mb-4">IN NO EVENT SHALL WE BE LIABLE FOR ANY DAMAGES WHATSOEVER  (INCLUDING, WITHOUT LIMITATION, INCIDENTAL, AND CONSEQUENTIAL  DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR  BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO USE  Solid’S, BANK’S, PLATFORM’S SERVICES OR WEBSITES OR PHONE  APPLICATIONS OR CONTENT THEREIN WHETHER BASED ON WARRANTY,  CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY,  EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR  LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES,  SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH STATES, OUR LIABILITY SHALL BE LIMITED TO THE GREATEST  EXTENT PERMITTED BY LAW. </p>
          <p className="mb-4 font-bold">d. Indemnification. </p>
          <p className="mb-4">You agree to defend, indemnify and hold harmless Solid and their respective officers, directors, employees, agents, and suppliers (collectively “Disclaiming Entities”) from and against any third party claim, suit, demand, loss, liability, damage,  action, proceeding or suits and related liabilities, damages,  settlements, penalties, fines, costs or expenses (including reasonable attorneys' fees and other litigation expenses) arising out of or relating to (i) your breach of any provision of these  Terms of Service; (ii) your actions and omissions in connection with your accounts or our services; (iii) our actions and omissions, provided that they are taken/omitted in accordance with this Terms of Service or your instructions; or (iv) your violation of any laws and regulations; or (v) your negligent or reckless act or omission or willful misconduct of your employees,  contractors, or agents. This provision shall survive the termination of these Terms of Service. </p>
          <p className="mb-4 font-bold">e. Binding Arbitration. </p>
          <p className="mb-4">Any controversy or claim arising out of or relating to these  Terms of Service, or the breach thereof, shall be settled by arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules, and judgment on the award rendered by the arbitrators may be entered in any court having jurisdiction thereof. In any arbitration arising out of or related to the Terms of Service, the arbitrators will award to the prevailing party, if any, the costs and attorneys’ fees reasonably incurred by the prevailing party in connection with those aspects of its claims or defenses on which it prevails, and any opposing awards of costs and attorneys’ fees awards will be offset. </p>
          <p className="mb-4">No class actions or similar process, and no joinder or consolidation of any claim with a claim of any other person or entity, shall be allowable in arbitration, without the written consent of both parties. The arbitrator shall have no authority to entertain any claim on behalf of a class, group, person, or entity who is not a named party to the arbitration, nor shall any arbitrator have authority to make any award for the benefit of,  or against, any class, group, person, or entity who is not a  named party to the arbitration. In the event that there is a  dispute about whether limiting arbitration to non-class proceedings, or to the named parties, is enforceable under applicable law, then that question shall be resolved by a court rather than by an arbitrator, and to the extent, it is determined that resolution of a claim must proceed on a class basis, it shall so proceed in a court of competent jurisdiction rather than in arbitration. </p>
          <p className="mb-4">The place of arbitration shall be San Francisco, CA, except to the extent, the arbitration involves Bank and/or your Account, or a third-party service provider of Solid as a party to the dispute, then Solid may in its sole discretion move the place of arbitration to the location of such arbitration proceedings to which you have previously agreed to in such agreements (See, your specific Account Agreement Arbitration sections for more information of the place of arbitration). </p>
          <p className="mb-4 font-bold">ARBITRATION WITH RESPECT TO A CLAIM IS BINDING AND NEITHER PARTY  WILL HAVE THE RIGHT TO LITIGATE THAT CLAIM THROUGH A COURT. IN  ARBITRATION THE PARTIES WILL NOT HAVE THE SAME RIGHTS THAT APPLY  IN COURT, SUCH AS THE RIGHT TO A TRIAL BY JUDGE OR JURY AND THE  RIGHT TO PARTICIPATE OR BE REPRESENTED IN PROCEEDINGS BROUGHT BY  OTHERS SUCH AS CLASS ACTIONS OR SIMILAR PROCEEDINGS. IN ADDITION,  THE RIGHT TO DISCOVERY AND THE RIGHT TO APPEAL MAY ALSO BE LIMITED  OR ELIMINATED IN ARBITRATION. ALL OF THESE JUDICIAL RIGHTS ARE  WAIVED WITH RESPECT TO CLAIMS THAT THE PARTIES ELECT TO ARBITRATE. </p>
          <p className="mb-4">All claims, findings, and settlements under this “Binding  Arbitration” shall be confidential information of Solid. You shall not disclose or reveal to employees, agents, Platform, or other third parties unless such information is already publicly available. Due to the unique nature of the confidential information, monetary damages may be inadequate to compensate us for your violation or threatened violation may cause irreparable injury to us and, in addition to any other remedies that may be available, in law, in equity or otherwise, we shall be entitled to seek injunctive relief against the threatened breach of confidentiality or the continuation of any such breach by you. </p>
          <p className="mb-4 font-bold">18. Other legal terms. </p>
          <p className="mb-4">The Terms of Service are governed by the laws of the State of California. You agree to submit to the exclusive personal jurisdiction of the state and federal courts in the State of California except as detailed in the “Binding Arbitration” Section.  If any provision of these Terms of Service is found to be invalid by a competent court, the invalidity of such provisions shall not affect the validity of the remaining provisions. Likewise, if we choose to terminate any provision in accordance with the termination provision, that termination shall not affect the termination of other provisions. </p>
          <p className="mb-4">If we fail to act on or enforce, any provision in the Terms of  Service, this shall not be construed as a waiver of that, or any other, provision. We will only grant waivers to specific provisions, for specific instances, in writing. The Terms of  Service constitute the entire agreement between you and us with respect to this website and supersedes all previous or contemporaneous agreements. The section headings are merely provided for convenience and shall not be given any legal import.  You may not assign your rights and obligations under these Terms of Service. The Terms of Service will inure to the benefit of our successors, assignees, licensees, and sublicensees.</p>

        </div>


      </main>
      <Footer />
    </>
  );
}
